name: One Click ROM Builder

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3 unzip zip

    - name: Download ROM
      run: |
        echo "Downloading ROM..."
        curl -L "${{ github.event.inputs.ROM_URL }}" -o rom.zip

    - name: Extract ROM
      run: |
        mkdir rom
        unzip -q rom.zip -d rom

    - name: Apply VoLTE/VoWiFi patch
      run: |
        python3 engine.py rom

    - name: Repack ROM
      run: |
        cd rom
        zip -r ../ROM-Patched.zip .
        cd ..

    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: ROM-VoLTE-PATCHED
        path: ROM-Patched.zip
